language: ruby

rvm:
- 2.6.8
- 2.7.4
- 3.0.2

install: bundle install --retry=3

before_install:
  - gem update bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.2.3"'
  - 'TEST_RAILS_VERSION="~> 6.0.3"'
  - 'TEST_RAILS_VERSION="~> 6.1.4"'
