language: ruby

rvm:
- 2.6.7
- 2.7.3
- 3.0.1

install: bundle install --retry=3

before_install:
  - gem update bundler

env:
  - 'TEST_RAILS_VERSION="~> 5.2.3"'
  - 'TEST_RAILS_VERSION="~> 6.0.3"'
  - 'TEST_RAILS_VERSION="~> 6.1.0"'
